-- не забыть проагрегировать DWH.RMD 
--and contr.VALID_TO_DTTM = to_date('2400-01-01', 'yyyy-mm-dd')
-- из-за проблем с коодировкой не забыть все сохранить через девелопер
-- RECONFIRMATNEW_APPROVALRESULT
-- RECONFIRMATNEW_COUNTER_FULLTM
-- RECONFIRMATNEW_COUNTER_WRKTM -> RECONFIRMATNEW_COUNTER_WRKTM
-- REPOYBNEREPOYBW_COUNTER_FULLTM -> REPOYBNEREPOYBW_COUNTER_FULLTM 
-- UNDERWRITNEW_APPROVALRESULTNM -> UNDERWRITNEW_APPROVALRESULTNM


select 

sysdate as insertDT,

-- account
ACCOUNTID,
CREATEDON,
DESCRIPTION,
EMAILADDRESS1,
INDUSTRYCODE,
INDUSTRYCODENAME,
ORGNAME,
NEW_4RELIABILITY_GROUP,
NEW_4RELIABILITY_GROUPNAME,
NEW_ACCOUNTGROUPIDNAME,
NEW_ACCOUNTINDUCTRY,
NEW_ACCOUNTINDUCTRYNAME,
NEW_AGENT,
NEW_BAZA1,
NEW_BAZA2,
NEW_BIRTHDAYDATE,
NEW_BLACK_LIST_DATE,
NEW_CEOCHANGE,
NEW_CEOCHANGENAME,
NEW_CHEKVERIFICATION,
NEW_CITYPHONE,
NEW_COMPANYSITE,
NEW_CONSENT,
NEW_CONTACTCENTRID,
NEW_CONTACTCENTRIDNAME,
NEW_COREMANAGERUALID,
NEW_COREMANAGERUALIDNAME,
NEW_DATE_APPOIMENT,
NEW_DATEVERIFICATION,
NEW_DUBLE1,
NEW_DUBLE2,
NEW_EMAIL,
NEW_EXPLOITATIONPL1,
NEW_EXPLOITATIONPLMAIL,
NEW_EXPLOITATIONPLMOBPHONE,
NEW_EXPLOITATIONPLPHONE,
NEW_EXPLOITATIONPLPROF,
NEW_FACTSDDRESS,
NEW_FACTSDDRESSNAME,
NEW_FIO,
NEW_FISICAL,
NEW_GENERALBUYER,
NEW_GENERALSUPLIER,
NEW_GUARANTOR,
NEW_INCIDENTSOURCE,
NEW_INCIDENTSOURCENAME,
NEW_INN,
NEW_INTEREST,
NEW_INTERNET,
NEW_KPP,
NEW_KY_CUSTOMER,
NEW_KY_SPESHLPR,
NEW_LEASEHOLDER,
NEW_LEGADDRESS,
NEW_LEGADDRESSNAME,
NEW_LEGALORGANIZATIONALFORM,
NEW_LEGALORGANIZATIONALFORMNAM,
NEW_MOBILEPHONE,
NEW_NUM1C,
NEW_OBLIGATIONS,
NEW_OFFICIALDEALER,
NEW_OGRN,
NEW_OKVEDID,
NEW_OKVEDIDNAME,
NEW_OWNERPL1,
NEW_OWNERPLMAIL,
NEW_OWNERPLMOBPHONE,
NEW_OWNERPLPHONE,
NEW_OWNERPLPROF,
NEW_PASSPORT,
NEW_PAYMENTOWNER,
NEW_PERFORMER1,
NEW_PERFORMERMAIL,
NEW_PERFORMERMOBPHONE,
NEW_PERFORMERPHONE,
NEW_PERFORMERPROF,
NEW_PHYSICALINN,
NEW_POSTADDRESS,
NEW_POSTADDRESSNAME,
NEW_PROFESSION,
NEW_REGISTRATIONADDRESS,
NEW_REGISTRATIONDATE,
NEW_REGULATIONSFZ223,
NEW_STATUS,
NEW_STATUSNAME,
NEW_SUBJECT,
NEW_SUPNAME,
NEW_SUPPLIER,
NEW_SUPPLIERCATEGORY,
NEW_SUPPLIERCATEGORYNAME,
NEW_SUPPLIERID,
NEW_SUPPLIERIDNAME,
NEW_SUPTYPE,
NEW_SUPTYPENAME,
NEW_TAXSYSTEM,
NEW_TAXSYSTEMNAME,
NEW_TERRITORY,
NEW_TERRITORYNAME,
NEW_UK,
NEW_UNITAR1,
NEW_WORKPHONE,
OWNERID,
OWNERIDNAME,
PREFERREDCONTACTMETHODCODE,
PREFERREDCONTACTMETHODCODENAME,
PRIMARYCONTACTID,
PRIMARYCONTACTIDNAME,
WEBSITEURL, 

-- opportynity

CUSTOMERID,
CUSTOMERIDNAME,
MODIFIEDON,
NAME,
NEW_4REL_GROUP_OPPORTUNITY,
NEW_ADDITIONALCONDITIONS,
NEW_AGENCYCONTRACTID,
NEW_AGENCYCONTRACTIDNAME,
NEW_AGENTID,
NEW_AGENTIDNAME,
NEW_ALLEXPRETISETASKSCLOSED,
NEW_APPROVALRESULT,
NEW_APPROVALRESULTNAME,
NEW_APPROVALROUTE,
NEW_APPROVALROUTENAME,
NEW_CONFIRMLITEMTOMIDMVALUE,
NEW_CONTRACTSUM,
NEW_CURRENCY,
NEW_DOCUMENT,
NEW_FACTADRESS,
NEW_FACTSUM,
NEW_FINANCESUM_INVESTREST_GK,
NEW_FRANCHISE,
NEW_HEADERCOREMANAGERUAL,
NEW_HEADERCOREMANAGERUALNAME,
NEW_HEADERMANAGERUALID,
NEW_HEADERMANAGERUALIDNAME,
NEW_INCLUDEAGENT,
NEW_INSPECTIONUAKR,
NEW_INSPECTIONUAKRNAME,
NEW_INSURANCERISK,
NEW_LEASAGREEMENTCONDCONFIRMED,
NEW_LEASEDEALSTOPFACTORS,
NEW_LEASEDEALSTOPFACTORSNAME,
NEW_LEASEOBJECT,
NEW_LEASESROK,
NEW_MIDDLEMANAGER,
NEW_MIDDLEMANAGERNAME,
NEW_NONFINANCIAL,
NEW_OPF,
NEW_OPT,
NEW_ORDER_FOR_SIGNING,
NEW_ORDER_FOR_SIGNINGNAME,
NEW_PLACE,
NEW_PODPRODUCT,
NEW_PODPRODUCTNAME,
NEW_PRODUCTCOST,
NEW_PRODUCTID,
NEW_PRODUCTIDNAME,
NEW_PROPERTYRISK,
NEW_QUANTITYLO,
NEW_RECOMMENDATIONSDONE,
NEW_REDEMPTIONPAYMENT,
NEW_ROUTINGBYMODEL,
NEW_SENTFORAPPROVAL,
NEW_SENTFORAPPROVALNAME,
NEW_STATUSCODEID,
NEW_STATUSCODEIDNAME,
NEW_STOPFACTORSAGREEMENTERID ,
NEW_STOPFACAGREEMENTERIDNAME,
NEW_SUMM,
NEW_SUSPENSIVECONDITIONS,
NEW_TAXATIONSYSTEM,
NEW_TOTALFINANCEOPPORTUNITYSUM,
NEW_TOTALFINANCINGSUM,
NEW_TOTALFINANCINGSUM_EXPRESS,
NEW_TOTALSUMDEALPERIOD,
NEW_TYPELO,
NEW_YEARMARGA,
OPPORTUNITYID,

NEW_ACCOUNTGROUPID,
NEW_NAME,
OWNINGBUSINESSUNIT,



ACCOUNTIDNAME,
ADDRESS1_ADDRESSID,
ADDRESS2_ADDRESSID,
ADDRESS3_ADDRESSID,
BIRTHDATE,
CONTACTID,
DONOTSENDMM,
EXCHANGERATE,
FIRSTNAME,
GENDERCODE,
GENDERCODENAME,
JOBTITLE,
LASTNAME,
MERGED,
MIDDLENAME,
MOBILEPHONE,
NEW_ACCEPTOR,
NEW_ACCTYPE,
NEW_ACCTYPENAME,
NEW_ADDRESS,
NEW_ANYTIME,
NEW_CITIZENSHIP1,
NEW_CONTACTPERSON,
NEW_CONTACTTYPE,
NEW_CONTACTTYPENAME,
NEW_FORWARDER,
NEW_JOBTITLEDAT,
NEW_JOBTITLEROD,
NEW_LIVELADRESS,
NEW_LIVELADRESSNAME,
NEW_NOMIDDLENAME,
NEW_OFFICALPRESENTATIVE,
NEW_OFFICIALREPRESENTATIVE,
NEW_PASPORTID,
NEW_PASPORTIDNAME,
NEW_PASS,
NEW_SIGNATURE,
NEW_SIGNER,
NEW_USTAV,
NEW_USTAVNAME,
ORIGINATINGLEADID,
ORIGINATINGLEADIDNAME,
OWNERIDTYPE,
PARENTCUSTOMERID,
PARENTCUSTOMERIDNAME,
PARENTCUSTOMERIDTYPE,
--PARENTCUSTOMERIDYOMINAME, -- нет такого поля 
TELEPHONE1,
TRANSACTIONCURRENCYID,
TRANSACTIONCURRENCYIDNAME,
VTBL_DATERECEIVEDSCORINGSCORE,
VTBL_IDBKI,
VTBL_MEMBERSHAREHOLDER,
VTBL_MEMSHAREHOLDER_ID,
VTBL_MEMSHAREHOLDER_IDNAME,
VTBL_SCORINGSCORE,
VTBL_SENDMM,
VTBL_STATUSSCORINGSCORE,
VTBL_STATUSSCORINGSCORENAME,





COMPANYNAME,
CONFIRMINTEREST,
DECISIONMAKER,
DONOTBULKEMAIL,
EVALUATEFIT,
FULLNAME,
LEADID,
LEADQUALITYCODE,
LEADQUALITYCODENAME,
NEW_AGENT_ACCOUNTID,
NEW_AGENT_ACCOUNTIDNAME,
NEW_ARCHIVE,
NEW_BUSINESSUNITID,
NEW_BUSINESSUNITIDNAME,
NEW_CALLCENTER,
NEW_CLIENTTYPE,
NEW_CLIENTTYPENAME,
NEW_CONTACTCENTR,
NEW_CONTACTIDNAME,
NEW_CONVERTATION,
NEW_FOREIGNCOMPANY,
NEW_GREENLIGHT,
NEW_INDUSTRYTYPE,
NEW_INDUSTRYTYPENAME,
NEW_INTERESTOPF,
NEW_INTERESTOPFNAME,
NEW_LANDING,
NEW_MOREYEAR,
NEW_NEW_CONTACT,
NEW_NUMBERLEAD,
NEW_REF_ACCOUNT,
NEW_REF_ACCOUNTNAME,
NEW_TYPE,
NEW_TYPENAME,
NEW_WEB,
PARENTACCOUNTID,
PARENTACCOUNTIDNAME,
PARENTCONTACTID,
PARENTCONTACTIDNAME,
QUALIFYINGOPPORTUNITYID,
QUALIFYINGOPPORTUNITYIDNAME,
VTBL_REVENUE_PER_YEARCODE,
VTBL_REVENUE_PER_YEARCODENAME,
VTBL_URL,
VTBL_UTM_CAMPAIGN,
VTBL_UTM_MEDIUM,
VTBL_UTM_SOURCE,
VTBL_UTM_TERM,


NEW_BIRTHDAY,
NEW_BIRTHPLACE,
NEW_CODE,
NEW_CONTACT,
NEW_CONTACTNAME,
--NEW_CONTACTYOMINAME, -- нет такого поля 
NEW_DOCNUMBER,
NEW_DOCTYPE,
NEW_DOCTYPENAME,
NEW_SERIA,
NEW_STARTDATE,
NEW_WHENGIVE,
NEW_WHOGIVE,
VTBL_ADDRESS2_LINE1,

RELGROUPS, 
RELMAX,

ACCOUNTCOMPANYSITE,
ACCOUNTREGISTRATIONDATE,
COUNTEDON,
CREDITMODELISCOUNTABLE,
FINANCESUM,
NEW_CONFIRMLEASITEMTOMIDMARKET,
NEW_CONTRACTNUMBER,
NEW_CREDITRISKDEFAULTEARLIER,
CREDITMODELRESULT,
NEW_FINANCESUM,
NEW_FRAUDRISKDEFAULTEARLIER,
FRAUDMODELRESULT,
NEW_LEASEAGREEMENTCONDITIONS,
NEW_LEASOBJECTID,
NEW_LEASOBJECTNAME,
NEW_RELIABILITY_GROUPS,
OPPORTUNITYCREDITRESULT,
OPPORTUNITYFRAUDRESULT,
OPPORTUNITYNAME,
PRODUCTLO,
PRODUCTOP,
QUOTE,
QUOTEID,
RISKMODELID,
SCORING_POINT_CALC_STAGE,


VERACTIVITYID,
VERACTUALEND,
VERACTUALSTART,
VERCREATEDON,
VERNEW_APPROVALRESULT,
VERNEW_APPROVALRESULTNAME,
VERNEW_COMMENTS,
VERNEW_COUNTER_FULLTIME,
VERNEW_COUNTER_WORKTIME,
VERNEW_HISTORY,
VERNEW_TYPE,
VERNEW_TYPENAME,
VERNEW_UZDL,



RECONFIRMATIONACTIVITYID,
RECONFIRMATIONACTUALEND,
RECONFIRMATIONACTUALSTART,
RECONFIRMATIONCREATEDON,
RECONFIRMATNEW_APPROVALRESULT,
RECONFIRMATNEW_APPROVALRESNAME,
RECONFIRMATIONNEW_COMMENTS,
RECONFIRMATNEW_COUNTER_FULLTM,
RECONFIRMATNEW_COUNTER_WRKTM,
RECONFIRMATIONNEW_HISTORY,
RECONFIRMATIONNEW_TYPE,
RECONFIRMATIONNEW_TYPENAME,
RECONFIRMATIONNEW_UZDL,



EXPOYBACTIVITYID,
EXPOYBACTUALEND,
EXPOYBACTUALSTART,
EXPOYBCREATEDON,
EXPOYBNEW_APPROVALRESULT,
EXPOYBNEW_APPROVALRESULTNAME,
EXPOYBNEW_COMMENTS,
EXPOYBNEW_COUNTER_FULLTIME,
EXPOYBNEW_COUNTER_WORKTIME,
EXPOYBNEW_HISTORY,
EXPOYBNEW_TYPE,
EXPOYBNEW_TYPENAME,
EXPOYBNEW_UZDL,

REPOYBACTIVITYID,
REPOYBACTUALEND,
REPOYBACTUALSTART,
REPOYBCREATEDON,
REPOYBNEW_APPROVALRESULT,
REPOYBNEW_APPROVALRESULTNAME,
REPOYBNEW_COMMENTS,
REPOYBNEREPOYBW_COUNTER_FULLTM,
REPOYBNEW_COUNTER_WORKTIME,
REPOYBNEW_HISTORY,
REPOYBNEW_TYPE,
REPOYBNEW_TYPENAME,
REPOYBNEW_UZDL,


EXPUAKRACTIVITYID,
EXPUAKRACTUALEND,
EXPUAKRACTUALSTART,
EXPUAKRCREATEDON,
EXPUAKRNEW_APPROVALRESULT,
EXPUAKRNEW_APPROVALRESULTNAME,
EXPUAKRNEW_COMMENTS,
EXPUAKRNEW_COUNTER_FULLTIME,
EXPUAKRNEW_COUNTER_WORKTIME,
EXPUAKRNEW_HISTORY,
EXPUAKRNEW_TYPE,
EXPUAKRNEW_TYPENAME,
EXPUAKRNEW_UZDL,


REPUAKRACTIVITYID,
REPUAKRACTUALEND,
REPUAKRACTUALSTART,
REPUAKRCREATEDON,
REPUAKRNEW_APPROVALRESULT,
REPUAKRNEW_APPROVALRESULTNAME,
REPUAKRNEW_COMMENTS,
REPUAKRNEW_COUNTER_FULLTIME,
REPUAKRNEW_COUNTER_WORKTIME,
REPUAKRNEW_HISTORY,
REPUAKRNEW_TYPE,
REPUAKRNEW_TYPENAME,
REPUAKRNEW_UZDL,



UNDERWRITACTIVITYID,
UNDERWRITACTUALEND,
UNDERWRITACTUALSTART,
UNDERWRITCREATEDON,
UNDERWRITNEW_APPROVALRESULT,
UNDERWRITNEW_APPROVALRESULTNM,
UNDERWRITNEW_COMMENTS,
UNDERWRITNEW_COUNTER_FULLTIME,
UNDERWRITNEW_COUNTER_WORKTIME,
UNDERWRITNEW_HISTORY,
UNDERWRITNEW_TYPE,
UNDERWRITNEW_TYPENAME,
UNDERWRITNEW_UZDL,



SOLUTIONDESACTIVITYID,
SOLUTIONDESACTUALEND,
SOLUTIONDESACTUALSTART,
SOLUTIONDESCREATEDON,
SOLUTIONDESNEW_APPROVALRESULT,
SOLUTIONDESNEW_APPROVALRESLTNM,
SOLUTIONDESNEW_COMMENTS,
SOLUTIONDESNEW_COUNTER_FULLTM,
SOLUTIONDESNEW_COUNTER_WORKTM,
SOLUTIONDESNEW_HISTORY,
SOLUTIONDESNEW_TYPE,
SOLUTIONDESNEW_TYPENAME,
SOLUTIONDESNEW_UZDL,


SOLUTIONDESKUFRACTIVITYID,
SOLUTIONDESKUFRACTUALEND,
SOLUTIONDESKUFRACTUALSTART,
SOLUTIONDESKUFRCREATEDON,
SLTNDESKUFRNEW_APPROVALRESULT,
SLTNDSKFRNW_APPROVALRESULTNAME,
SOLUTIONDESKUFRNEW_COMMENTS,
SLTNDSKFRNEW_COUNTER_FULLTIME,
SLTNDSKFRNEW_COUNTER_WORKTIME,
SOLUTIONDESKUFRNEW_HISTORY,
SOLUTIONDESKUFRNEW_TYPE,
SOLUTIONDESKUFRNEW_TYPENAME,
SOLUTIONDESKUFRNEW_UZDL,

REAPPROVACTIVITYID,
REAPPROVACTUALEND,
REAPPROVACTUALSTART,
REAPPROVCREATEDON,
REAPPROVNEW_APPROVALRESULT,
REAPPROVNEW_APPROVALRESULTNAME,
REAPPROVNEW_COMMENTS,
REAPPROVNEW_COUNTER_FULLTIME,
REAPPROVNEW_COUNTER_WORKTIME,
REAPPROVNEW_HISTORY,
REAPPROVNEW_TYPE,
REAPPROVNEW_TYPENAME,
REAPPROVNEW_UZDL


 
from 
(


			select 
							
						Max(ac.TIMESLOTSTART) over (partition by ac.ACCOUNTID) as ac_TIMESLOTSTART, -- у Иры надо уточнить, в рамках чего групиировка
						RMD.CountedOn as rmd_CountedOn, 
						Max(op.TIMESLOTSTART) over(partition by op.CUSTOMERID)  as op_TIMESLOTSTART,

						AC.ACCOUNTID,
						AC.CREATEDON,
						AC.DESCRIPTION,
						AC.EMAILADDRESS1,
						AC.INDUSTRYCODE,
						AC.INDUSTRYCODENAME,
						AC.NAME as ORGNAME,
						AC.NEW_4RELIABILITY_GROUP,
						AC.NEW_4RELIABILITY_GROUPNAME,
						AC.NEW_ACCOUNTGROUPIDNAME,
						AC.NEW_ACCOUNTINDUCTRY,
						AC.NEW_ACCOUNTINDUCTRYNAME,
						AC.NEW_AGENT,
						AC.NEW_BAZA1,
						AC.NEW_BAZA2,
						AC.NEW_BIRTHDAYDATE,
						AC.NEW_BLACK_LIST_DATE,
						AC.NEW_CEOCHANGE,
						AC.NEW_CEOCHANGENAME,
						AC.NEW_CHEKVERIFICATION,
						AC.NEW_CITYPHONE,
						AC.NEW_COMPANYSITE,
						AC.NEW_CONSENT,
						AC.NEW_CONTACTCENTRID,
						AC.NEW_CONTACTCENTRIDNAME,
						AC.NEW_COREMANAGERUALID,
						AC.NEW_COREMANAGERUALIDNAME,
						AC.NEW_DATE_APPOIMENT,
						AC.NEW_DATEVERIFICATION,
						AC.NEW_DUBLE1,
						AC.NEW_DUBLE2,
						AC.NEW_EMAIL,
						AC.NEW_EXPLOITATIONPL1,
						AC.NEW_EXPLOITATIONPLMAIL,
						AC.NEW_EXPLOITATIONPLMOBPHONE,
						AC.NEW_EXPLOITATIONPLPHONE,
						AC.NEW_EXPLOITATIONPLPROF,
						AC.NEW_FACTSDDRESS,
						AC.NEW_FACTSDDRESSNAME,
						AC.NEW_FIO,
						AC.NEW_FISICAL,
						AC.NEW_GENERALBUYER,
						AC.NEW_GENERALSUPLIER,
						AC.NEW_GUARANTOR,
						AC.NEW_INCIDENTSOURCE,
						AC.NEW_INCIDENTSOURCENAME,
						AC.NEW_INN,
						AC.NEW_INTEREST,
						AC.NEW_INTERNET,
						AC.NEW_KPP,
						AC.NEW_KY_CUSTOMER,
						AC.NEW_KY_SPESHLPR,
						AC.NEW_LEASEHOLDER,
						AC.NEW_LEGADDRESS,
						AC.NEW_LEGADDRESSNAME,
						AC.NEW_LEGALORGANIZATIONALFORM,
						AC.NEW_LEGALORGANIZATIONALFORMNAM,
						AC.NEW_MOBILEPHONE,
						AC.NEW_NUM1C,
						AC.NEW_OBLIGATIONS,
						AC.NEW_OFFICIALDEALER,
						AC.NEW_OGRN,
						AC.NEW_OKVEDID,
						AC.NEW_OKVEDIDNAME,
						AC.NEW_OWNERPL1,
						AC.NEW_OWNERPLMAIL,
						AC.NEW_OWNERPLMOBPHONE,
						AC.NEW_OWNERPLPHONE,
						AC.NEW_OWNERPLPROF,
						AC.NEW_PASSPORT,
						AC.NEW_PAYMENTOWNER,
						AC.NEW_PERFORMER1,
						AC.NEW_PERFORMERMAIL,
						AC.NEW_PERFORMERMOBPHONE,
						AC.NEW_PERFORMERPHONE,
						AC.NEW_PERFORMERPROF,
						AC.NEW_PHYSICALINN,
						AC.NEW_POSTADDRESS,
						AC.NEW_POSTADDRESSNAME,
						AC.NEW_PROFESSION,
						AC.NEW_REGISTRATIONADDRESS,
						AC.NEW_REGISTRATIONDATE,
						AC.NEW_REGULATIONSFZ223,
						AC.NEW_STATUS,
						AC.NEW_STATUSNAME,
						AC.NEW_SUBJECT,
						AC.NEW_SUPNAME,
						AC.NEW_SUPPLIER,
						AC.NEW_SUPPLIERCATEGORY,
						AC.NEW_SUPPLIERCATEGORYNAME,
						AC.NEW_SUPPLIERID,
						AC.NEW_SUPPLIERIDNAME,
						AC.NEW_SUPTYPE,
						AC.NEW_SUPTYPENAME,
						AC.NEW_TAXSYSTEM,
						AC.NEW_TAXSYSTEMNAME,
						AC.NEW_TERRITORY,
						AC.NEW_TERRITORYNAME,
						AC.NEW_UK,
						AC.NEW_UNITAR1,
						AC.NEW_WORKPHONE,
						AC.OWNERID,
						AC.OWNERIDNAME,
						AC.PREFERREDCONTACTMETHODCODE,
						AC.PREFERREDCONTACTMETHODCODENAME,
						AC.PRIMARYCONTACTID,
						AC.PRIMARYCONTACTIDNAME,
						AC.WEBSITEURL,


						op.CUSTOMERID,
						op.CUSTOMERIDNAME,
						op.MODIFIEDON,
						op.NAME,
						op.NEW_4REL_GROUP_OPPORTUNITY,
						op.NEW_ADDITIONALCONDITIONS,
						op.NEW_AGENCYCONTRACTID,
						op.NEW_AGENCYCONTRACTIDNAME,
						op.NEW_AGENTID,
						op.NEW_AGENTIDNAME,
						op.NEW_ALLEXPRETISETASKSCLOSED,
						op.NEW_APPROVALRESULT,
						op.NEW_APPROVALRESULTNAME,
						op.NEW_APPROVALROUTE,
						op.NEW_APPROVALROUTENAME,
						op.NEW_CONFIRMLITEMTOMIDMVALUE,
						op.NEW_CONTRACTSUM,
						op.NEW_CURRENCY,
						op.NEW_DOCUMENT,
						op.NEW_FACTADRESS,
						op.NEW_FACTSUM,
						op.NEW_FINANCESUM_INVESTREST_GK,
						op.NEW_FRANCHISE,
						op.NEW_HEADERCOREMANAGERUAL,
						op.NEW_HEADERCOREMANAGERUALNAME,
						op.NEW_HEADERMANAGERUALID,
						op.NEW_HEADERMANAGERUALIDNAME,
						op.NEW_INCLUDEAGENT,
						op.NEW_INSPECTIONUAKR,
						op.NEW_INSPECTIONUAKRNAME,
						op.NEW_INSURANCERISK,
						op.NEW_LEASAGREEMENTCONDCONFIRMED,
						op.NEW_LEASEDEALSTOPFACTORS,
						op.NEW_LEASEDEALSTOPFACTORSNAME,
						op.NEW_LEASEOBJECT,
						op.NEW_LEASESROK,
						op.NEW_MIDDLEMANAGER,
						op.NEW_MIDDLEMANAGERNAME,
						op.NEW_NONFINANCIAL,
						op.NEW_OPF,
						op.NEW_OPT,
						op.NEW_ORDER_FOR_SIGNING,
						op.NEW_ORDER_FOR_SIGNINGNAME,
						op.NEW_PLACE,
						op.NEW_PODPRODUCT,
						op.NEW_PODPRODUCTNAME,
						op.NEW_PRODUCTCOST,
						op.NEW_PRODUCTID,
						op.NEW_PRODUCTIDNAME,
						op.NEW_PROPERTYRISK,
						op.NEW_QUANTITYLO,
						op.NEW_RECOMMENDATIONSDONE,
						op.NEW_REDEMPTIONPAYMENT,
						op.NEW_ROUTINGBYMODEL,
						op.NEW_SENTFORAPPROVAL,
						op.NEW_SENTFORAPPROVALNAME,
						op.NEW_STATUSCODEID,
						op.NEW_STATUSCODEIDNAME,
						op.NEW_STOPFACTORSAGREEMENTERID ,
						op.NEW_STOPFACAGREEMENTERIDNAME,
						op.NEW_SUMM,
						op.NEW_SUSPENSIVECONDITIONS,
						op.NEW_TAXATIONSYSTEM,
						op.NEW_TOTALFINANCEOPPORTUNITYSUM,
						op.NEW_TOTALFINANCINGSUM,
						op.NEW_TOTALFINANCINGSUM_EXPRESS,
						op.NEW_TOTALSUMDEALPERIOD,
						op.NEW_TYPELO,
						op.NEW_YEARMARGA,
						op.OPPORTUNITYID,

						newAcGroup.NEW_ACCOUNTGROUPID,
						newAcGroup.NEW_NAME,
						newAcGroup.OWNINGBUSINESSUNIT,



						con.ACCOUNTIDNAME,
						con.ADDRESS1_ADDRESSID,
						con.ADDRESS2_ADDRESSID,
						con.ADDRESS3_ADDRESSID,
						con.BIRTHDATE,
						con.CONTACTID,
						con.DONOTSENDMM,
						con.EXCHANGERATE,
						con.FIRSTNAME,
						con.GENDERCODE,
						con.GENDERCODENAME,
						con.JOBTITLE,
						con.LASTNAME,
						con.MERGED,
						con.MIDDLENAME,
						con.MOBILEPHONE,
						con.NEW_ACCEPTOR,
						con.NEW_ACCTYPE,
						con.NEW_ACCTYPENAME,
						con.NEW_ADDRESS,
						con.NEW_ANYTIME,
						con.NEW_CITIZENSHIP1,
						con.NEW_CONTACTPERSON,
						con.NEW_CONTACTTYPE,
						con.NEW_CONTACTTYPENAME,
						con.NEW_FORWARDER,
						con.NEW_JOBTITLEDAT,
						con.NEW_JOBTITLEROD,
						con.NEW_LIVELADRESS,
						con.NEW_LIVELADRESSNAME,
						con.NEW_NOMIDDLENAME,
						con.NEW_OFFICALPRESENTATIVE,
						con.NEW_OFFICIALREPRESENTATIVE,
						con.NEW_PASPORTID,
						con.NEW_PASPORTIDNAME,
						con.NEW_PASS,
						con.NEW_SIGNATURE,
						con.NEW_SIGNER,
						con.NEW_USTAV,
						con.NEW_USTAVNAME,
						con.ORIGINATINGLEADID,
						con.ORIGINATINGLEADIDNAME,
						con.OWNERIDTYPE,
						con.PARENTCUSTOMERID,
						con.PARENTCUSTOMERIDNAME,
						con.PARENTCUSTOMERIDTYPE,
--						con.PARENTCUSTOMERIDYOMINAME,  -- нет такого поля 
						con.TELEPHONE1,
						con.TRANSACTIONCURRENCYID,
						con.TRANSACTIONCURRENCYIDNAME,
						con.VTBL_DATERECEIVEDSCORINGSCORE,
						con.VTBL_IDBKI,
						con.VTBL_MEMBERSHAREHOLDER,
						con.VTBL_MEMSHAREHOLDER_ID,
						con.VTBL_MEMSHAREHOLDER_IDNAME,con.VTBL_SCORINGSCORE,
						con.VTBL_SENDMM,
						con.VTBL_STATUSSCORINGSCORE,
						con.VTBL_STATUSSCORINGSCORENAME,

						
						crmLead.COMPANYNAME,
						crmLead.CONFIRMINTEREST,
						crmLead.DECISIONMAKER,
						crmLead.DONOTBULKEMAIL,
						crmLead.EVALUATEFIT,
						crmLead.FULLNAME,
						crmLead.LEADID,
						crmLead.LEADQUALITYCODE,
						crmLead.LEADQUALITYCODENAME,
						crmLead.NEW_AGENT_ACCOUNTID,
						crmLead.NEW_AGENT_ACCOUNTIDNAME,
						crmLead.NEW_ARCHIVE,
						crmLead.NEW_BUSINESSUNITID,
						crmLead.NEW_BUSINESSUNITIDNAME,
						crmLead.NEW_CALLCENTER,
						crmLead.NEW_CLIENTTYPE,
						crmLead.NEW_CLIENTTYPENAME,
						crmLead.NEW_CONTACTCENTR,
						crmLead.NEW_CONTACTIDNAME,
						crmLead.NEW_CONVERTATION,
						crmLead.NEW_FOREIGNCOMPANY,
						crmLead.NEW_GREENLIGHT,
						crmLead.NEW_INDUSTRYTYPE,
						crmLead.NEW_INDUSTRYTYPENAME,
						crmLead.NEW_INTERESTOPF,
						crmLead.NEW_INTERESTOPFNAME,
						crmLead.NEW_LANDING,
						crmLead.NEW_MOREYEAR,
						crmLead.NEW_NEW_CONTACT,
						crmLead.NEW_NUMBERLEAD,
						crmLead.NEW_REF_ACCOUNT,
						crmLead.NEW_REF_ACCOUNTNAME,
						crmLead.NEW_TYPE,
						crmLead.NEW_TYPENAME,
						crmLead.NEW_WEB,
						crmLead.PARENTACCOUNTID,
						crmLead.PARENTACCOUNTIDNAME,
						crmLead.PARENTCONTACTID,
						crmLead.PARENTCONTACTIDNAME,
						crmLead.QUALIFYINGOPPORTUNITYID,
						crmLead.QUALIFYINGOPPORTUNITYIDNAME,
						crmLead.VTBL_REVENUE_PER_YEARCODE,
						crmLead.VTBL_REVENUE_PER_YEARCODENAME,
						crmLead.VTBL_URL,
						crmLead.VTBL_UTM_CAMPAIGN,
						crmLead.VTBL_UTM_MEDIUM,
						crmLead.VTBL_UTM_SOURCE,
						crmLead.VTBL_UTM_TERM,
						

						newHumanDocs.NEW_BIRTHDAY,
						newHumanDocs.NEW_BIRTHPLACE,
						newHumanDocs.NEW_CODE,
						newHumanDocs.NEW_CONTACT,
						newHumanDocs.NEW_CONTACTNAME,
--						newHumanDocs.NEW_CONTACTYOMINAME, -- нет такого поля 
						newHumanDocs.NEW_DOCNUMBER,
						newHumanDocs.NEW_DOCTYPE,
						newHumanDocs.NEW_DOCTYPENAME,
						newHumanDocs.NEW_SERIA,
						newHumanDocs.NEW_STARTDATE,
						newHumanDocs.NEW_WHENGIVE,
						newHumanDocs.NEW_WHOGIVE,
						newHumanDocs.VTBL_ADDRESS2_LINE1,
						
						relGroup.RELGROUPS, 
						relGroup.RELMAX,

						
						rmd.ACCOUNTCOMPANYSITE,
						rmd.ACCOUNTREGISTRATIONDATE,
						rmd.COUNTEDON,
						rmd.CREDITMODELISCOUNTABLE,
						rmd.FINANCESUM,
						rmd.NEW_CONFIRMLEASITEMTOMIDMARKET,
						rmd.NEW_CONTRACTNUMBER,
						rmd.NEW_CREDITRISKDEFAULTEARLIER,
						rmd.CREDITMODELRESULT,
						rmd.NEW_FINANCESUM,
						rmd.NEW_FRAUDRISKDEFAULTEARLIER,
						rmd.FRAUDMODELRESULT,
						rmd.NEW_LEASEAGREEMENTCONDITIONS,
						rmd.NEW_LEASOBJECTID,
						rmd.NEW_LEASOBJECTNAME,
						rmd.NEW_RELIABILITY_GROUPS,
						rmd.OPPORTUNITYCREDITRESULT,
						rmd.OPPORTUNITYFRAUDRESULT,
						rmd.OPPORTUNITYNAME,
						rmd.PRODUCTLO,
						rmd.PRODUCTOP,
						rmd.QUOTE,
						rmd.QUOTEID,
						rmd.RISKMODELID,
						rmd.SCORING_POINT_CALC_STAGE,


						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.ACTIVITYID end as VERACTIVITYID,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.ACTUALEND end as VERACTUALEND,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.ACTUALSTART end as VERACTUALSTART,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.CREATEDON end as VERCREATEDON,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_APPROVALRESULT end as VERNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_APPROVALRESULTNAME end as VERNEW_APPROVALRESULTNAME,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_COMMENTS end as VERNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_COUNTER_FULLTIME end as VERNEW_COUNTER_FULLTIME,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_COUNTER_WORKTIME end as VERNEW_COUNTER_WORKTIME,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_HISTORY end as VERNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_TYPE end as VERNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_TYPENAME end as VERNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) = 'ВЕРИФИКАЦИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' then tskNew.NEW_UZDL end as VERNEW_UZDL,						


						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.ACTIVITYID end as RECONFIRMATIONACTIVITYID,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.ACTUALEND end as RECONFIRMATIONACTUALEND,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.ACTUALSTART end as RECONFIRMATIONACTUALSTART,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.CREATEDON end as RECONFIRMATIONCREATEDON,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_APPROVALRESULT end as RECONFIRMATNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_APPROVALRESULTNAME end as RECONFIRMATNEW_APPROVALRESNAME,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_COMMENTS end as RECONFIRMATIONNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_COUNTER_FULLTIME end as RECONFIRMATNEW_COUNTER_FULLTM,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_COUNTER_WORKTIME end as RECONFIRMATNEW_COUNTER_WRKTM,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_HISTORY end as RECONFIRMATIONNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_TYPE end as RECONFIRMATIONNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_TYPENAME end as RECONFIRMATIONNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ПОДТВЕРЖДЕНИЕ%' then tskNew.NEW_UZDL end as RECONFIRMATIONNEW_UZDL,						


						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.ACTIVITYID end as EXPOYBACTIVITYID,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.ACTUALEND end as EXPOYBACTUALEND,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.ACTUALSTART end as EXPOYBACTUALSTART,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.CREATEDON end as EXPOYBCREATEDON,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_APPROVALRESULT end as EXPOYBNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_APPROVALRESULTNAME end as EXPOYBNEW_APPROVALRESULTNAME,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_COMMENTS end as EXPOYBNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_COUNTER_FULLTIME end as EXPOYBNEW_COUNTER_FULLTIME,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_COUNTER_WORKTIME end as EXPOYBNEW_COUNTER_WORKTIME,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_HISTORY end as EXPOYBNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_TYPE end as EXPOYBNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_TYPENAME end as EXPOYBNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (УОБ)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_UZDL end as EXPOYBNEW_UZDL,


						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.ACTIVITYID end as REPOYBACTIVITYID,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.ACTUALEND end as REPOYBACTUALEND,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.ACTUALSTART end as REPOYBACTUALSTART,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.CREATEDON end as REPOYBCREATEDON,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_APPROVALRESULT end as REPOYBNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_APPROVALRESULTNAME end as REPOYBNEW_APPROVALRESULTNAME,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_COMMENTS end as REPOYBNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_COUNTER_FULLTIME end as REPOYBNEREPOYBW_COUNTER_FULLTM,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_COUNTER_WORKTIME end as REPOYBNEW_COUNTER_WORKTIME,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_HISTORY end as REPOYBNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_TYPE end as REPOYBNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_TYPENAME end as REPOYBNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УОБ') then tskNew.NEW_UZDL end as REPOYBNEW_UZDL,
						
						
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.ACTIVITYID end as EXPUAKRACTIVITYID,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.ACTUALEND end as EXPUAKRACTUALEND,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.ACTUALSTART end as EXPUAKRACTUALSTART,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.CREATEDON end as EXPUAKRCREATEDON,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_APPROVALRESULT end as EXPUAKRNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_APPROVALRESULTNAME end as EXPUAKRNEW_APPROVALRESULTNAME,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_COMMENTS end as EXPUAKRNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_COUNTER_FULLTIME end as EXPUAKRNEW_COUNTER_FULLTIME,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_COUNTER_WORKTIME end as EXPUAKRNEW_COUNTER_WORKTIME,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_HISTORY end as EXPUAKRNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_TYPE end as EXPUAKRNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_TYPENAME end as EXPUAKRNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) in ('ЭКСПЕРТИЗА (РИСК)', 'ПИ ЭКСПЕРТНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_UZDL end as EXPUAKRNEW_UZDL,
						

						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.ACTIVITYID end as REPUAKRACTIVITYID,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.ACTUALEND end as REPUAKRACTUALEND,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.ACTUALSTART end as REPUAKRACTUALSTART,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.CREATEDON end as REPUAKRCREATEDON,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_APPROVALRESULT end as REPUAKRNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_APPROVALRESULTNAME end as REPUAKRNEW_APPROVALRESULTNAME,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_COMMENTS end as REPUAKRNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_COUNTER_FULLTIME end as REPUAKRNEW_COUNTER_FULLTIME,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_COUNTER_WORKTIME end as REPUAKRNEW_COUNTER_WORKTIME,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_HISTORY end as REPUAKRNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_TYPE end as REPUAKRNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_TYPENAME end as REPUAKRNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) in ('ПИ ПОВТОРНАЯ ПРОВЕРКА УАКР (АНАЛИЗ РИСКОВ)') then tskNew.NEW_UZDL end as REPUAKRNEW_UZDL,


						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.ACTIVITYID end as UNDERWRITACTIVITYID,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.ACTUALEND end as UNDERWRITACTUALEND,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.ACTUALSTART end as UNDERWRITACTUALSTART,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.CREATEDON end as UNDERWRITCREATEDON,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_APPROVALRESULT end as UNDERWRITNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_APPROVALRESULTNAME end as UNDERWRITNEW_APPROVALRESULTNM,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_COMMENTS end as UNDERWRITNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_COUNTER_FULLTIME end as UNDERWRITNEW_COUNTER_FULLTIME,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_COUNTER_WORKTIME end as UNDERWRITNEW_COUNTER_WORKTIME,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_HISTORY end as UNDERWRITNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_TYPE end as UNDERWRITNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_TYPENAME end as UNDERWRITNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) in ('ОДОБРЕНИЕ АНДЕРРАЙТЕР') then tskNew.NEW_UZDL end as UNDERWRITNEW_UZDL,

						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.ACTIVITYID end as SOLUTIONDESACTIVITYID,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.ACTUALEND end as SOLUTIONDESACTUALEND,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.ACTUALSTART end as SOLUTIONDESACTUALSTART,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.CREATEDON end as SOLUTIONDESCREATEDON,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_APPROVALRESULT end as SOLUTIONDESNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_APPROVALRESULTNAME end as SOLUTIONDESNEW_APPROVALRESLTNM,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_COMMENTS end as SOLUTIONDESNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_COUNTER_FULLTIME end as SOLUTIONDESNEW_COUNTER_FULLTM,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_COUNTER_WORKTIME end as SOLUTIONDESNEW_COUNTER_WORKTM,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_HISTORY end as SOLUTIONDESNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_TYPE end as SOLUTIONDESNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_TYPENAME end as SOLUTIONDESNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КЛАС ПО ЛС%' or upper(trim(tskNew.subject)) like '%КЛАС по 4ой группе%')  then tskNew.NEW_UZDL end as SOLUTIONDESNEW_UZDL,

						
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.ACTIVITYID end as SOLUTIONDESKUFRACTIVITYID,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.ACTUALEND end as SOLUTIONDESKUFRACTUALEND,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.ACTUALSTART end as SOLUTIONDESKUFRACTUALSTART,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.CREATEDON end as SOLUTIONDESKUFRCREATEDON,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_APPROVALRESULT end as SLTNDESKUFRNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_APPROVALRESULTNAME end as SLTNDSKFRNW_APPROVALRESULTNAME,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_COMMENTS end as SOLUTIONDESKUFRNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_COUNTER_FULLTIME end as SLTNDSKFRNEW_COUNTER_FULLTIME,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_COUNTER_WORKTIME end as SLTNDSKFRNEW_COUNTER_WORKTIME,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_HISTORY end as SOLUTIONDESKUFRNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_TYPE end as SOLUTIONDESKUFRNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_TYPENAME end as SOLUTIONDESKUFRNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) = 'ОФОРМЛЕНИЕ РЕШЕНИЯ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and (upper(trim(tskNew.subject)) like '%КУФР%' and upper(trim(tskNew.subject)) like '%ОДОБРЕНИЕ%')  then tskNew.NEW_UZDL end as SOLUTIONDESKUFRNEW_UZDL,

						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.ACTIVITYID end as REAPPROVACTIVITYID,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.ACTUALEND end as REAPPROVACTUALEND,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.ACTUALSTART end as REAPPROVACTUALSTART,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.CREATEDON end as REAPPROVCREATEDON,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_APPROVALRESULT end as REAPPROVNEW_APPROVALRESULT,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_APPROVALRESULTNAME end as REAPPROVNEW_APPROVALRESULTNAME,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_COMMENTS end as REAPPROVNEW_COMMENTS,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_COUNTER_FULLTIME end as REAPPROVNEW_COUNTER_FULLTIME,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_COUNTER_WORKTIME end as REAPPROVNEW_COUNTER_WORKTIME,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_HISTORY end as REAPPROVNEW_HISTORY,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_TYPE end as REAPPROVNEW_TYPE,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_TYPENAME end as REAPPROVNEW_TYPENAME,
						case when upper(trim(tskNew.new_typename)) = 'ПИ ПОВТОРНОЕ ОДОБРЕНИЕ' and upper(trim(tskNew.new_uzdl)) = 'ДА' and upper(trim(tskNew.subject)) like '%ПИ ПОВТОРНОЕ ОДОБРЕНИЕ%' then tskNew.NEW_UZDL end as REAPPROVNEW_UZDL

						
						
						
						
							
				from DWH.ACCOUNT ac 

				
				left join DWH.RELLGROUP relGroup  on relGroup.ACCOUNTID = ac.ACCOUNTID
				
				
				
				left join DWH.OPPORTUNITY op on ac.ACCOUNTID = op.CUSTOMERID
												and op.VALID_TO_DTTM = to_date('2400-01-01', 'yyyy-mm-dd')	
				
				left join 
				(
					select 
						max(OPPORTUNITYID) as OPPORTUNITYID,
						
						
						max(ACCOUNTCOMPANYSITE) as ACCOUNTCOMPANYSITE,
						max(ACCOUNTREGISTRATIONDATE) as ACCOUNTREGISTRATIONDATE,
						--COUNTEDON,
						max(CREDITMODELISCOUNTABLE) as CREDITMODELISCOUNTABLE,
						max(FINANCESUM) as FINANCESUM,
							
						max(NEW_CONFIRMLEASITEMTOMIDMARKET) as NEW_CONFIRMLEASITEMTOMIDMARKET,
						max(NEW_CONTRACTNUMBER) as NEW_CONTRACTNUMBER,
						max(NEW_CREDITRISKDEFAULTEARLIER) as NEW_CREDITRISKDEFAULTEARLIER,
						max(CREDITMODELRESULT) as CREDITMODELRESULT,
						max(NEW_FINANCESUM) as NEW_FINANCESUM,
						max(NEW_FRAUDRISKDEFAULTEARLIER) as NEW_FRAUDRISKDEFAULTEARLIER,
						max(FRAUDMODELRESULT) as FRAUDMODELRESULT,
						max(NEW_LEASEAGREEMENTCONDITIONS) as NEW_LEASEAGREEMENTCONDITIONS,
						max(NEW_LEASOBJECTID) as NEW_LEASOBJECTID,
						max(NEW_LEASOBJECTNAME) as NEW_LEASOBJECTNAME,
						max(NEW_RELIABILITY_GROUPS) as NEW_RELIABILITY_GROUPS,
						max(OPPORTUNITYCREDITRESULT) as OPPORTUNITYCREDITRESULT,
						max(OPPORTUNITYFRAUDRESULT) as OPPORTUNITYFRAUDRESULT,
						--OPPORTUNITYNAME,
						max(PRODUCTLO) as PRODUCTLO,
						max(PRODUCTOP) as PRODUCTOP,
						max(QUOTE) as QUOTE,
						max(QUOTEID) as QUOTEID,
						max(RISKMODELID) as RISKMODELID,
						'XZ' as SCORING_POINT_CALC_STAGE,
						
						
						OPPORTUNITYNAME, 
						COUNTEDON 
					from DWH.RMD 
					group by -- какая то странная групиировка, почему потом поле группировки не участвует в джоине? почему не группировать по OPPORTUNITYID
						OPPORTUNITYNAME, 
						COUNTEDON
				) rmd on rmd.OPPORTUNITYID = op.OPPORTUNITYID

				
				left join 
				(
					select 
						NEW_ACCOUNTGROUPID,
						NEW_NAME,
						OWNINGBUSINESSUNIT,

						Max(TIMESLOTSTART) over (partition by NEW_ACCOUNTGROUPID) as max_TIMESLOTSTART -- надо узать у Иры, по какому over или группировка
						
					from DWH.NEW_ACCOUNTGROUP
					where VALID_TO_DTTM = to_date('2400-01-01', 'yyyy-mm-dd')				
				) newAcGroup  on newAcGroup.NEW_ACCOUNTGROUPID = ac.NEW_ACCOUNTGROUPID
								and newAcGroup.max_TIMESLOTSTART < rmd.COUNTEDON
				
				left join 
				(
					select 
						ACCOUNTID, 
						ORIGINATINGLEADID,
												
						ACCOUNTIDNAME,
						ADDRESS1_ADDRESSID,
						ADDRESS2_ADDRESSID,
						ADDRESS3_ADDRESSID,
						BIRTHDATE,
						CONTACTID,
						DONOTSENDMM,
						EXCHANGERATE,
						FIRSTNAME,
						GENDERCODE,
						GENDERCODENAME,
						JOBTITLE,
						LASTNAME,
						MERGED,
						MIDDLENAME,
						MOBILEPHONE,
						NEW_ACCEPTOR,
						NEW_ACCTYPE,
						NEW_ACCTYPENAME,
						NEW_ADDRESS,
						NEW_ANYTIME,
						NEW_CITIZENSHIP1,
						NEW_CONTACTPERSON,
						NEW_CONTACTTYPE,
						NEW_CONTACTTYPENAME,
						NEW_FORWARDER,
						NEW_JOBTITLEDAT,
						NEW_JOBTITLEROD,
						NEW_LIVELADRESS,
						NEW_LIVELADRESSNAME,
						NEW_NOMIDDLENAME,
						NEW_OFFICALPRESENTATIVE,
						NEW_OFFICIALREPRESENTATIVE,
						NEW_PASPORTID,
						NEW_PASPORTIDNAME,
						NEW_PASS,
						NEW_SIGNATURE,
						NEW_SIGNER,
						NEW_USTAV,
						NEW_USTAVNAME,
					--	ORIGINATINGLEADID, -- выше упоминается 
						ORIGINATINGLEADIDNAME,
						OWNERIDTYPE,
						PARENTCUSTOMERID,
						PARENTCUSTOMERIDNAME,
						PARENTCUSTOMERIDTYPE,
--						PARENTCUSTOMERIDYOMINAME,  -- нет такого поля 
						TELEPHONE1,
						TRANSACTIONCURRENCYID,
						TRANSACTIONCURRENCYIDNAME,
						VTBL_DATERECEIVEDSCORINGSCORE,
						VTBL_IDBKI,
						VTBL_MEMBERSHAREHOLDER,
						VTBL_MEMSHAREHOLDER_ID,
						VTBL_MEMSHAREHOLDER_IDNAME,
						VTBL_SCORINGSCORE,
						VTBL_SENDMM,
						VTBL_STATUSSCORINGSCORE,
						VTBL_STATUSSCORINGSCORENAME,						
						
				
						
						Max(TIMESLOTSTART) over (partition by ACCOUNTID) as max_TIMESLOTSTART -- надо узать у Иры, по какому over или группировка
					from DWH.CONTACT
					where 
						VALID_TO_DTTM = to_date('2400-01-01', 'yyyy-mm-dd')
				) con on con.ACCOUNTID = ac.ACCOUNTID 
						and con.max_TIMESLOTSTART < rmd.COUNTEDON
										

				
				left join 
				(
					select 
						LEADID, 
						NEW_CONTACTID,
						
						
						COMPANYNAME,
						CONFIRMINTEREST,
						DECISIONMAKER,
						DONOTBULKEMAIL,
						EVALUATEFIT,
						FULLNAME,
					--	LEADID, -- есть выше 
						LEADQUALITYCODE,
						LEADQUALITYCODENAME,
						NEW_AGENT_ACCOUNTID,
						NEW_AGENT_ACCOUNTIDNAME,
						NEW_ARCHIVE,
						NEW_BUSINESSUNITID,
						NEW_BUSINESSUNITIDNAME,
						NEW_CALLCENTER,
						NEW_CLIENTTYPE,
						NEW_CLIENTTYPENAME,
						NEW_CONTACTCENTR,
						NEW_CONTACTIDNAME,
						NEW_CONVERTATION,
						NEW_FOREIGNCOMPANY,
						NEW_GREENLIGHT,
						NEW_INDUSTRYTYPE,
						NEW_INDUSTRYTYPENAME,
						NEW_INTERESTOPF,
						NEW_INTERESTOPFNAME,
						NEW_LANDING,
						NEW_MOREYEAR,
						NEW_NEW_CONTACT,
						NEW_NUMBERLEAD,
						NEW_REF_ACCOUNT,
						NEW_REF_ACCOUNTNAME,
						NEW_TYPE,
						NEW_TYPENAME,
						NEW_WEB,
						PARENTACCOUNTID,
						PARENTACCOUNTIDNAME,
						PARENTCONTACTID,
						PARENTCONTACTIDNAME,
						QUALIFYINGOPPORTUNITYID,
						QUALIFYINGOPPORTUNITYIDNAME,
						VTBL_REVENUE_PER_YEARCODE,
						VTBL_REVENUE_PER_YEARCODENAME,
						VTBL_URL,
						VTBL_UTM_CAMPAIGN,
						VTBL_UTM_MEDIUM,
						VTBL_UTM_SOURCE,
						VTBL_UTM_TERM,				
						
						
						
						Max(TIMESLOTSTART) over (partition by LEADID) as max_TIMESLOTSTART -- надо узать у Иры, по какому over или группировка
					from DWH.CRM_LEAD
					where VALID_TO_DTTM = to_date('2400-01-01', 'yyyy-mm-dd')
				) crmLead on crmLead.LEADID = con.ORIGINATINGLEADID 
												and crmLead.max_TIMESLOTSTART < rmd.COUNTEDON				
				
				left join 
				
				(
					select 
					

						max(ACTIVITYID) KEEP (DENSE_RANK FIRST ORDER BY createdon) as ACTIVITYID,
						max(ACTUALEND) KEEP (DENSE_RANK FIRST ORDER BY createdon) as ACTUALEND,
						max(ACTUALSTART) KEEP (DENSE_RANK FIRST ORDER BY createdon) as ACTUALSTART,
						max(CREATEDON) as CREATEDON,
						max(NEW_APPROVALRESULT) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_APPROVALRESULT,
						max(NEW_APPROVALRESULTNAME) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_APPROVALRESULTNAME,
						max(NEW_COMMENTS) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_COMMENTS,
						max(NEW_COUNTER_FULLTIME) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_COUNTER_FULLTIME,
						max(NEW_COUNTER_WORKTIME) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_COUNTER_WORKTIME,
						max(NEW_HISTORY) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_HISTORY,
						max(NEW_TYPE) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_TYPE,
						max(NEW_TYPENAME) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_TYPENAME,
						max(NEW_UZDL) KEEP (DENSE_RANK FIRST ORDER BY createdon) as NEW_UZDL,
						max(SUBJECT) KEEP (DENSE_RANK FIRST ORDER BY createdon) as SUBJECT,
						
						REGARDINGOBJECTID
						
					from DWH.TASKNEW tskNew
					
					where 
						new_decision_date is not null
						and VALID_TO_DTTM = to_date('2400-01-01', 'yyyy-mm-dd')	 
						and trim(upper(NEW_STATUSNAME)) = upper('Закрыта')
						
					group by REGARDINGOBJECTID
				
				) tskNew on tskNew.REGARDINGOBJECTID = op.OPPORTUNITYID
												-- добавить ограничения на CREATEDON + NEW_DECISION_DATE + еще всякая ересь в прозе 
												

				left join 
				(
					select 
						NEW_CONTACT, 
						
						
						NEW_BIRTHDAY,
						NEW_BIRTHPLACE,
						NEW_CODE,
						--NEW_CONTACT,
						NEW_CONTACTNAME,
						-- NEW_CONTACTYOMINAME, -- нет такого поля 
						NEW_DOCNUMBER,
						NEW_DOCTYPE,
						NEW_DOCTYPENAME,
						NEW_SERIA,
						NEW_STARTDATE,
						NEW_WHENGIVE,
						NEW_WHOGIVE,
						VTBL_ADDRESS2_LINE1,
						
						
						
						
						Max(TIMESLOTSTART) over (partition by NEW_CONTACT) as max_TIMESLOTSTART -- надо узать у Иры, по какому over или группировка
					from DWH.NEW_HUMANDOCS 
					where VALID_TO_DTTM = to_date('2400-01-01', 'yyyy-mm-dd')	 
					
				) newHumanDocs on  newHumanDocs.NEW_CONTACT = crmLead.NEW_CONTACTID
									and newHumanDocs.max_TIMESLOTSTART < rmd.COUNTEDON				

				
				where ac.VALID_TO_DTTM = to_date('2400-01-01', 'yyyy-mm-dd')
) mainSel	
	
where ac_TIMESLOTSTART < rmd_CountedOn
	
	and op_TIMESLOTSTART < rmd_CountedOn