select * from DWH.ACCOUNT;
select * from DWH.OPPORTUNITY;
select * from DWH.RELLGROUP;
select * from DWH.NEW_ACCOUNTGROUP;
select * from DWH.CONTACT;
select * from DWH.CRM_LEAD;
select * from DWH.NEW_HUMANDOCS;
select * from DWH.RMD;
select * from DWH.TASKNEW;
