CREATE TABLE DWH.FV_CONTRACTS_TERMS (
    CONTRACTS_TERMS_KEY NUMBER primary key ,
    CONTRACTS_TERMS_NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(4000)
);
COMMENT ON COLUMN DWH.FV_CONTRACTS_TERMS.CONTRACTS_TERMS_KEY IS 'Ключ условий контракта';
COMMENT ON COLUMN DWH.FV_CONTRACTS_TERMS.CONTRACTS_TERMS_NAME IS 'Название условий контракта';
COMMENT ON COLUMN DWH.FV_CONTRACTS_TERMS.DESCRIPTION IS 'Описание';
COMMENT ON TABLE DWH.FV_CONTRACTS_TERMS  IS 'Справочник условий контрактов (для расчета справедливой ставки)';
