-- Create table
create table DWH.RMD
(
    riskmodelid                    VARCHAR2(36),
    opportunityname                VARCHAR2(100),
    opportunityid                  VARCHAR2(36),
    new_contractnumber             VARCHAR2(200),
    new_contractid                 VARCHAR2(36),
    new_leasobjectname             VARCHAR2(100),
    new_leasobjectid               VARCHAR2(36),
    creditmodeliscountable         NUMBER,
    creditmodelvalues              VARCHAR2(1000),
    fraudmodeliscountable          NUMBER,
    fraudmodelvalues               VARCHAR2(1000),
    countedon                      DATE,
    creditmodelresult              NUMBER,
    fraudmodelresult               NUMBER,
    creditscore                    NUMBER,
    fraudscore                     NUMBER,
    productop                      VARCHAR2(200),
    productlo                      VARCHAR2(200),
    financesum                     NUMBER,
    new_reliability_groups         VARCHAR2(1000),
    statuscode                     VARCHAR2(100),
    quote                          VARCHAR2(100),
    quoteid                        VARCHAR2(36),
    new_inn                        VARCHAR2(40),
    creditfields                   VARCHAR2(2000),
    creditbindings                 VARCHAR2(2000),
    fraudfields                    VARCHAR2(2000),
    fraudbindings                  VARCHAR2(2000),
    opportunitycreatedon           DATE,
    opportunitycreditresult        NUMBER,
    opportunityfraudresult         NUMBER,
    accountregistrationdate        DATE,
    accountcompanysite             VARCHAR2(400),
    new_financesum                 NUMBER,
    new_nonfinancial               NUMBER,
    new_propertyrisk               NUMBER,
    new_confirmleasitemtomidmarket NUMBER,
    new_allexpretisetasksclosed    NUMBER,
    new_leaseagreementconditions   NUMBER,
    new_routingbymodel             NUMBER,
    new_approvalroute              NUMBER,
    new_creditriskmodel            NUMBER,
    new_fraudriskmodel             NUMBER,
    new_creditriskdefaultearlier   NUMBER,
    new_fraudriskdefaultearlier    NUMBER,
    creditmodelversion             NUMBER,
    fraudmodelversion              NUMBER,
    sessionkey                     NUMBER,
    insertationdate                DATE,
    scoringscore                   NUMBER
);
-- Create/Recreate indexes
create index DWH.RMD_I01 on DWH.RMD (OPPORTUNITYNAME)
  compress;


