--------------------------------------------------------
--  File created - суббота-Сентябрь-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PD_CORP
--------------------------------------------------------

  CREATE TABLE "DWH"."PD_CORP" 
   (	"RANK_MODEL_KEY" NUMBER, 
	"RANK_MODEL" VARCHAR2(60 BYTE), 
	"RAT_ON_DATE" VARCHAR2(16 BYTE), 
	"PD1_MACRO" NUMBER, 
	"PD2_MACRO" NUMBER, 
	"PD3_MACRO" NUMBER, 
	"PD4_MACRO" NUMBER, 
	"PD5_MACRO" NUMBER, 
	"PD6_MACRO" NUMBER, 
	"PD7_MACRO" NUMBER, 
	"PD8_MACRO" NUMBER, 
	"PD9_MACRO" NUMBER, 
	"PD10_MACRO" NUMBER, 
	"VALID_FROM_DTTM" DATE, 
	"VALID_TO_DTTM" DATE, 
	"ST_DATE" DATE, 
	"PD1_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD1_MACRO" WHEN 1 THEN 1 ELSE "PD1_MACRO" END) VIRTUAL VISIBLE , 
	"PD2_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD1_MACRO" WHEN 1 THEN 1 ELSE "PD2_MACRO"-"PD1_MACRO" END) VIRTUAL VISIBLE , 
	"PD3_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD2_MACRO" WHEN 1 THEN 1 ELSE "PD3_MACRO"-"PD2_MACRO" END) VIRTUAL VISIBLE , 
	"PD4_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD3_MACRO" WHEN 1 THEN 1 ELSE "PD4_MACRO"-"PD3_MACRO" END) VIRTUAL VISIBLE , 
	"PD5_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD4_MACRO" WHEN 1 THEN 1 ELSE "PD5_MACRO"-"PD4_MACRO" END) VIRTUAL VISIBLE , 
	"PD6_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD5_MACRO" WHEN 1 THEN 1 ELSE "PD6_MACRO"-"PD5_MACRO" END) VIRTUAL VISIBLE , 
	"PD7_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD6_MACRO" WHEN 1 THEN 1 ELSE "PD7_MACRO"-"PD6_MACRO" END) VIRTUAL VISIBLE , 
	"PD8_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD7_MACRO" WHEN 1 THEN 1 ELSE "PD8_MACRO"-"PD7_MACRO" END) VIRTUAL VISIBLE , 
	"PD9_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD8_MACRO" WHEN 1 THEN 1 ELSE "PD9_MACRO"-"PD8_MACRO" END) VIRTUAL VISIBLE , 
	"PD10_MARG" NUMBER GENERATED ALWAYS AS (CASE "PD9_MACRO" WHEN 1 THEN 1 ELSE "PD10_MACRO"-"PD9_MACRO" END) VIRTUAL VISIBLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

   COMMENT ON TABLE "DWH"."PD_CORP"  IS 'Справочник PD - Корпораты';
--------------------------------------------------------
--  DDL for Index U_PD_CORP
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."U_PD_CORP" ON "DWH"."PD_CORP" ("RANK_MODEL", "RAT_ON_DATE", "ST_DATE", "VALID_TO_DTTM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  Constraints for Table PD_CORP
--------------------------------------------------------

  ALTER TABLE "DWH"."PD_CORP" MODIFY ("RANK_MODEL_KEY" NOT NULL ENABLE);
