--------------------------------------------------------
--  File created - вторник-Сентябрь-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RATING_MODEL
--------------------------------------------------------

  CREATE TABLE "DWH"."RATING_MODEL" 
   (	"RATING_MODEL_KEY" NUMBER, 
	"RATING_MODEL_1C_CD" VARCHAR2(9 BYTE), 
	"DELETE_FLG" CHAR(1 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"RATING_AGENCY_KEY" NUMBER, 
	"FILE_ID" NUMBER, 
	"SESS_NO" NUMBER, 
	"VALID_FROM_DTTM" DATE, 
	"VALID_TO_DTTM" DATE, 
	"PROCESS_KEY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
--------------------------------------------------------
--  DDL for Index RATING_MODEL#PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."RATING_MODEL#PK" ON "DWH"."RATING_MODEL" ("RATING_MODEL_KEY", "VALID_TO_DTTM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
--------------------------------------------------------
--  Constraints for Table RATING_MODEL
--------------------------------------------------------

  ALTER TABLE "DWH"."RATING_MODEL" ADD CONSTRAINT "RATING_MODEL#PK" PRIMARY KEY ("RATING_MODEL_KEY", "VALID_TO_DTTM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "DWH"."RATING_MODEL" MODIFY ("RATING_MODEL_KEY" NOT NULL ENABLE);
