--------------------------------------------------------
--  File created - суббота-Сентябрь-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REF_LGD
--------------------------------------------------------

  CREATE TABLE "DWH"."REF_LGD" 
   (	"LGD_TYPE_CD" VARCHAR2(200 BYTE), 
	"LEASING_SUBJECT_TYPE_CD" VARCHAR2(200 BYTE), 
	"LGD" NUMBER, 
	"BEGIN_DT" DATE, 
	"END_DT" DATE, 
	"VALID_FROM_DTTM" DATE, 
	"VALID_TO_DTTM" DATE, 
	"PROCESS_KEY" NUMBER, 
	"FILE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index U_REF_LGD
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."U_REF_LGD" ON "DWH"."REF_LGD" ("LGD_TYPE_CD", "LEASING_SUBJECT_TYPE_CD", "BEGIN_DT", "VALID_TO_DTTM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
